baseURL: "https://how-blog-is-built.iamwoz.com/"
languageCode: "en-GB"
title: "woz"
theme: "uozu-xmin"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Blog
      url: "blog/"
      weight: 2
