baseURL: "https://iamwoz.com/"
languageCode: "en-GB"
title: "woz"
theme: "uozu-xmin"

disableKinds:
  - "taxonomy"
ignoreErrors:
  - "error-disable-taxonomy"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Blog
      url: "blog/"
      weight: 2
